apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-s3-resources
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - >
              aws s3 cp s3://upraisedsandbox/code/service_name/ /workspace/ --recursive &&
              echo "Resources copied from S3";
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAWJLSYC6E63JMIE43"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      containers:
        - name: runner
          image: public.ecr.aws/v0c8x1b5/socket:latest
          ports:
            - containerPort: 3001
            - containerPort: 4200
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAWJLSYC6E63JMIE43"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            # Bounty $25 Use ephemeral-storage to add space limits here
            requests:
              # cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              # cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: service_name
spec:
  selector:
    app: service_name
  ports:
    - protocol: TCP
      name: ws
      port: 3001
      targetPort: 3001
    - protocol: TCP
      name: user
      port: 4200
      targetPort: 4200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service_name
spec:
  ingressClassName: nginx
  rules:
  - host: service_name.sandbox.upraised.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service_name
            port:
              number: 3001
  - host: service_name.box.upraised.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service_name
            port:
              number: 4200

